// UI strings — English
export default {
  common: {
    back: 'Back', close: 'Close', confirm: 'Confirm', cancel: 'Cancel', skip: 'Skip', proceed: 'Proceed',
    leave: 'Leave', ok: 'OK', continue: 'Continue', upright: 'Upright', reversed: 'Reversed', locked: 'Locked',
    unknown: '???', gold: '{n} gold', hp: 'HP', done: 'Done', none: 'None', take: 'Take', choose: 'Choose',
  },
  title: {
    tagline: 'Every card has two faces.',
    sub: 'A tarot roguelite deckbuilder',
    continue: 'Continue', newRun: 'New Run', compendium: 'Compendium', settings: 'Settings',
    runInfo: '{char} · Act {act} · Floor {floor}',
    level: 'Arcana {level}', insight: '{cur} / {next} insight', maxLevel: '{cur} insight · every arcanum revealed',
    abandonTitle: 'Abandon the current run?',
    abandonBody: 'Starting over ends the run in progress. It counts as a defeat, and insight earned so far is kept.',
    abandonOk: 'Abandon & start',
  },
  settings: {
    title: 'Settings', lang: 'Language', sfx: 'Sound effects', music: 'Music', fast: 'Fast animations',
    shake: 'Screen shake', mainMenu: 'Main menu', abandon: 'Abandon run',
    abandonTitle: 'Abandon this run?', abandonBody: 'The run ends as a defeat. Insight earned so far is kept.',
    abandonOk: 'Abandon run',
    reset: 'Erase all progress', resetTitle: 'Erase all progress?',
    resetBody: 'Unlocks, insight, records and the current run will be deleted. This can’t be undone.',
    resetOk: 'Erase everything', resetDone: 'All progress erased.',
  },
  notice: {
    run: 'A saved run couldn’t be read. It was set aside, not deleted.',
    meta: 'Saved progress couldn’t be read. It was set aside, not deleted.',
    settings: 'Settings couldn’t be read and were reset.',
    nostorage: 'This browser mode can’t save progress.',
  },
  charselect: {
    title: 'Draw your arcanum', start: 'Begin the reading', locked: 'Sealed',
    unlockHint: 'Defeat an Act I boss, or reach Arcana 3.',
    hp: '{n} HP', startRelic: 'Starting relic', startDeck: 'Starting deck',
    omen: 'Omen', omenNone: 'No omen', omenLevel: 'Omen {n}',
    omenHint: 'Win at your highest omen to unlock the next one.',
    stats: '{runs} runs · {wins} wins · best floor {best}',
    omens: [
      'No modifiers.',
      'Common foes have 10% more HP.',
      'Elites and bosses begin combat with 1 Might.',
      'Resting heals 20% instead of 30%.',
      'Begin each run carrying the curse Doubt.',
      'Bosses have 20% more HP.',
    ],
  },
  top: { act: 'Act {n}', floor: 'Floor {n}', deck: 'Deck', map: 'Map', menu: 'Menu', use: 'Use', drop: 'Discard', emptySlot: 'Empty potion slot' },
  acts: { 1: 'The Ember Wilds', 2: 'The Drowned Court', 3: 'The Glass Citadel' },
  map: { choose: 'Choose your path', boss: 'Boss', viewOnly: 'The path ahead' },
  node: { combat: 'Battle', elite: 'Elite', event: 'Unknown', shop: 'Merchant', rest: 'Sanctuary', treasure: 'Treasure', boss: 'Boss' },
  combat: {
    endTurn: 'End Turn', energy: 'Energy', flips: 'Flips', flip: 'Flip', draw: 'Draw pile', discard: 'Discard pile',
    vanish: 'Vanished', yourTurn: 'Your turn', enemyTurn: 'Enemy turn', turn: 'Turn {n}', victory: 'Victory',
    defeat: 'Defeat', noEnergy: 'Not enough energy', unplayable: 'This card can’t be played',
    noFlips: 'No flips left this turn', stuck: 'Stuck — can’t flip this turn', handFull: 'Your hand is full',
    pickTarget: 'Choose a target', empty: 'Empty', choose: 'Choose {n}', chooseUpTo: 'Choose up to {n}',
    confirmPick: 'Confirm', noTarget: 'No valid target',
  },
  intent: {
    attack: 'Attack', attackDebuff: 'Attack and hex', attackBlock: 'Attack and defend', block: 'Defend',
    buff: 'Empower', debuff: 'Hex', summon: 'Summon', special: 'Something strange', unknown: 'Unknown',
    dmg: 'Deals {dmg} damage', dmgTimes: 'Deals {dmg} damage {times} times',
  },
  reward: {
    title: 'Spoils', bossTitle: 'Boss vanquished', gold: '{n} gold', card: 'Add a card to your deck',
    potion: 'Potion', relic: 'Relic', potionsFull: 'Potion slots are full', chooseCard: 'Choose a card',
    skipCards: 'Skip cards', proceed: 'Proceed',
  },
  shop: {
    title: 'The Curio Merchant', remove: 'Card removal', removeDesc: 'Remove one card from your deck',
    sold: 'Sold', buy: 'Buy', poor: 'Not enough gold', leave: 'Leave', chooseRemove: 'Choose a card to remove',
    potionsFull: 'Potion slots are full',
  },
  rest: {
    title: 'Sanctuary', rest: 'Rest', restDesc: 'Heal {n} HP', refine: 'Refine', refineDesc: 'Upgrade a card',
    chooseRefine: 'Choose a card to refine', nothing: 'Every card is already refined', done: 'The candle gutters out.',
  },
  treasure: { title: 'A sealed reliquary', open: 'Open', empty: 'Empty' },
  bossRelic: { title: 'Claim a boss relic', skip: 'Take nothing' },
  event: { continue: 'Continue', fight: 'Fight' },
  select: {
    remove: 'Choose a card to remove', upgrade: 'Choose a card to refine', duplicate: 'Choose a card to copy',
    transform: 'Choose a card to transform', swap: 'Choose a card to turn over for good',
  },
  result: {
    win: 'The spread is complete.', lose: 'The reading ends here.', floor: 'Floor reached',
    elites: 'Elites slain', bosses: 'Bosses slain', kills: 'Foes defeated', insight: 'Insight earned',
    levelUp: 'Arcana {n} reached', unlocked: 'Newly revealed', charUnlocked: 'The Magician answers your call.',
    omenUnlocked: 'Omen {n} unlocked', toTitle: 'Return to title', again: 'Read again',
  },
  deck: { title: 'Deck', count: '{n} cards', empty: 'No cards here' },
  compendium: {
    title: 'Compendium', cards: 'Cards', relics: 'Relics', fool: 'The Fool', magician: 'The Magician',
    neutral: 'Colorless', found: '{n} / {m} discovered', sealed: 'Not yet discovered',
  },
  card: {
    attack: 'Attack', skill: 'Skill', power: 'Power', curse: 'Curse', status: 'Status',
    basic: 'Basic', common: 'Common', uncommon: 'Uncommon', rare: 'Rare', special: 'Special',
    onFlip: 'On flip', cost: 'Cost', x: 'X',
  },
  tutorial: {
    play: 'Tap a card, then tap an enemy — or drag the card onto it.',
    flip: 'Every card has two faces. Playing a card turns it over. Tap ↻ to flip one card for free each turn.',
    intent: 'The sign above each enemy shows what it will do on its turn.',
    end: 'Out of energy? End your turn.',
    gotIt: 'Got it',
  },
  prompt: {
    pick: 'Choose a card', flip: 'Choose a card to flip', discard: 'Choose a card to discard',
    vanish: 'Choose a card to vanish', upgrade: 'Choose a card to upgrade', discover: 'Choose a card to add to your hand',
    retain: 'Choose a card to keep', top: 'Choose a card to put on top of your draw pile',
  },
  fx: { blocked: 'Blocked' },
};
