// UI 문자열 — 한국어
export default {
  common: {
    back: '뒤로', close: '닫기', confirm: '확인', cancel: '취소', skip: '건너뛰기', proceed: '계속',
    leave: '떠나기', ok: '확인', continue: '계속', upright: '정방향', reversed: '역방향', locked: '잠김',
    unknown: '???', gold: '{n} 골드', hp: '체력', done: '완료', none: '없음',
  },
  title: {
    tagline: '모든 카드에는 두 얼굴이 있다.',
    sub: '타로 로그라이트 덱빌딩',
    continue: '이어하기', newRun: '새 게임', compendium: '도감', settings: '설정',
    runInfo: '{char} · {act}막 · {floor}층',
    level: '아르카나 {level}', insight: '통찰 {cur} / {next}', maxLevel: '통찰 {cur} · 모든 아르카나 공개',
    abandonTitle: '진행 중인 게임을 포기할까요?',
    abandonBody: '새로 시작하면 지금 게임은 패배로 끝납니다. 지금까지 얻은 통찰은 남습니다.',
    abandonOk: '포기하고 시작',
  },
  settings: {
    title: '설정', lang: '언어', sfx: '효과음', music: '음악', fast: '빠른 연출', shake: '화면 흔들림',
    mainMenu: '타이틀로', abandon: '게임 포기',
    abandonTitle: '이번 게임을 포기할까요?', abandonBody: '패배로 끝납니다. 지금까지 얻은 통찰은 남습니다.',
    abandonOk: '포기하기',
    reset: '모든 진행 삭제', resetTitle: '모든 진행을 삭제할까요?',
    resetBody: '해금, 통찰, 기록, 진행 중인 게임이 모두 지워집니다. 되돌릴 수 없습니다.',
    resetOk: '모두 삭제', resetDone: '모든 진행을 삭제했습니다.',
  },
  notice: {
    run: '저장된 게임을 읽지 못했습니다. 지우지 않고 따로 보관해 두었습니다.',
    meta: '저장된 진행을 읽지 못했습니다. 지우지 않고 따로 보관해 두었습니다.',
    settings: '설정을 읽지 못해 기본값으로 되돌렸습니다.',
    nostorage: '이 브라우저 모드에서는 진행이 저장되지 않습니다.',
  },
  charselect: {
    title: '당신의 아르카나를 뽑으세요', start: '점을 치다', locked: '봉인됨',
    unlockHint: '1막 보스를 쓰러뜨리거나 아르카나 3에 도달하세요.',
    hp: '체력 {n}', startRelic: '시작 유물', startDeck: '시작 덱',
    omen: '징조', omenNone: '징조 없음', omenLevel: '징조 {n}',
    omenHint: '가장 높은 징조에서 승리하면 다음 단계가 열립니다.',
    stats: '{runs}판 · {wins}승 · 최고 {best}층',
    omens: [
      '변화 없음.',
      '일반 적의 체력이 10% 늘어납니다.',
      '정예와 보스가 힘 1을 가지고 전투를 시작합니다.',
      '휴식의 회복량이 30%에서 20%로 줄어듭니다.',
      '저주 "의심"을 들고 시작합니다.',
      '보스의 체력이 20% 늘어납니다.',
    ],
  },
  top: { act: '{n}막', floor: '{n}층', deck: '덱', map: '지도', menu: '메뉴', use: '사용', drop: '버리기', emptySlot: '빈 물약 칸' },
  acts: { 1: '잿불 황야', 2: '가라앉은 궁정', 3: '유리 성채' },
  map: { choose: '길을 고르세요', boss: '보스', viewOnly: '앞으로의 길' },
  node: { combat: '전투', elite: '정예', event: '미지', shop: '상인', rest: '성소', treasure: '보물', boss: '보스' },
  combat: {
    endTurn: '턴 종료', energy: '에너지', flips: '뒤집기', flip: '뒤집기', draw: '뽑을 더미', discard: '버린 더미',
    vanish: '소멸', yourTurn: '나의 턴', enemyTurn: '적의 턴', turn: '{n}턴', victory: '승리',
    defeat: '패배', noEnergy: '에너지가 부족합니다', unplayable: '사용할 수 없는 카드입니다',
    noFlips: '이번 턴에는 더 뒤집을 수 없습니다', stuck: '걸림 — 이번 턴에는 뒤집을 수 없습니다', handFull: '손패가 가득 찼습니다',
    pickTarget: '대상을 고르세요', empty: '비어 있음', choose: '{n}장 고르기', chooseUpTo: '최대 {n}장 고르기',
    confirmPick: '확인', noTarget: '고를 수 있는 대상이 없습니다',
  },
  intent: {
    attack: '공격', attackDebuff: '공격과 저주', attackBlock: '공격과 방어', block: '방어',
    buff: '강화', debuff: '저주', summon: '소환', special: '알 수 없는 기운', unknown: '알 수 없음',
    dmg: '피해 {dmg}', dmgTimes: '피해 {dmg} × {times}회',
  },
  reward: {
    title: '전리품', bossTitle: '보스 격파', gold: '{n} 골드', card: '덱에 카드 추가',
    potion: '물약', relic: '유물', potionsFull: '물약 칸이 가득 찼습니다', chooseCard: '카드를 고르세요',
    skipCards: '카드 건너뛰기', proceed: '계속',
  },
  shop: {
    title: '골동품 상인', remove: '카드 제거', removeDesc: '덱에서 카드 한 장을 없앱니다',
    sold: '판매됨', poor: '골드가 부족합니다', leave: '떠나기', chooseRemove: '제거할 카드를 고르세요',
    potionsFull: '물약 칸이 가득 찼습니다',
  },
  rest: {
    title: '성소', rest: '휴식', restDesc: '체력 {n} 회복', refine: '정련', refineDesc: '카드 한 장 강화',
    chooseRefine: '정련할 카드를 고르세요', nothing: '모든 카드가 이미 정련되었습니다', done: '촛불이 잦아듭니다.',
  },
  treasure: { title: '봉인된 성유물함', open: '열기', empty: '비어 있음' },
  bossRelic: { title: '보스 유물을 고르세요', skip: '가져가지 않기' },
  event: { continue: '계속' },
  select: {
    remove: '제거할 카드를 고르세요', upgrade: '정련할 카드를 고르세요', duplicate: '복제할 카드를 고르세요',
    transform: '변환할 카드를 고르세요', swap: '영원히 뒤집어 둘 카드를 고르세요',
  },
  result: {
    win: '점괘가 완성되었다.', lose: '점괘는 여기서 끝난다.', floor: '도달한 층',
    elites: '처치한 정예', bosses: '처치한 보스', kills: '쓰러뜨린 적', insight: '얻은 통찰',
    levelUp: '아르카나 {n} 도달', unlocked: '새로 드러난 것', charUnlocked: '마법사가 부름에 응했습니다.',
    omenUnlocked: '징조 {n} 해금', toTitle: '타이틀로', again: '다시 점치기',
  },
  deck: { title: '덱', count: '{n}장', empty: '카드가 없습니다' },
  compendium: {
    title: '도감', cards: '카드', relics: '유물', fool: '바보', magician: '마법사',
    neutral: '무색', found: '{n} / {m} 발견', sealed: '아직 발견하지 못했습니다',
  },
  card: {
    attack: '공격', skill: '스킬', power: '파워', curse: '저주', status: '상태이상',
    basic: '기본', common: '일반', uncommon: '고급', rare: '희귀', special: '특수',
    onFlip: '뒤집힐 때', cost: '비용', x: 'X',
  },
  tutorial: {
    play: '카드를 누른 뒤 적을 누르세요. 카드를 적 위로 끌어다 놓아도 됩니다.',
    flip: '모든 카드에는 두 얼굴이 있습니다. 카드를 쓰면 뒤집힙니다. 턴마다 한 장은 ↻ 로 공짜로 뒤집을 수 있습니다.',
    intent: '적 머리 위의 표시는 그 적이 자기 턴에 할 행동입니다.',
    end: '에너지를 다 썼다면 턴을 종료하세요.',
    gotIt: '알겠습니다',
  },
};
